FROM bitnami/spark:3.5.4

USER root

# 패키지 설치
RUN install_packages \
    gcc \
    g++ \
    make \
    pkg-config \
    libfreetype6-dev \
    libpng-dev \
    libjpeg-dev \
    python3-dev \
    python3-pip

RUN pip install --no-cache-dir numpy pandas pyarrow

USER 1001
